config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :subcategories
  resources :categories
  resources :subjects
  resources :languages
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/language.rb
class Language < ApplicationRecord
    has_many :video, dependent: :destroy
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: %i[ show edit update destroy ]

  # GET /languages or /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1 or /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages or /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: "Language was successfully created." }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1 or /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: "Language was successfully updated." }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1 or /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: "Language was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def language_params
      params.require(:language).permit(:name)
    end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_with(model: language) do |form| %>
  <% if language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
        <% language.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing Language</h1>
<br />
<%= render 'form', language: @language %>
<br />
<%= link_to 'Show', @language, class:"btn btn-secondary" %>
<%= link_to 'Back', categories_path, class:"btn btn-dark" %>

app/views/languages/index.html.erb
<h1>Languages</h1>
<br />
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= language.id %></td>
        <td><%= link_to language.name, language %></td>
        <td><%= link_to 'Edit', edit_language_path(language), class:"btn btn-success" %></td>
        <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Language', new_language_path, class:"btn btn-primary" %>

app/views/languages/new.html.erb
<h1>New Language</h1>
<br />
<%= render 'form', language: @language %>
<br />
<%= link_to 'Back', languages_path, class:"btn btn-dark" %>

app/views/languages/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @language.name %>
</p>
<br />
<%= link_to 'Edit', edit_language_path(@language), class:"btn btn-success" %>
<%= link_to 'Back', languages_path, class:"btn btn-dark" %>