config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :subcategories
  resources :categories
  resources :subjects
  resources :languages
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Archiving App', root_path, class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Users", home_index_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Languages", languages_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Subjects", subjects_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Subcategories", subcategories_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Videos", videos_path, class:"nav-link" %>
        </li>

      <% else %>
        
      <% end %>

      
      
    </ul>
    <ul class="navbar-nav ml-auto">

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>

      
      
    </ul>
    <%# <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>
  </div>
</nav>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>Email</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.email %></td>                 
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<% end %>